import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Nav from "./nav";

const inter = localFont({
  src: [
    {
      path: "../fonts/InterVariable.woff2",
    },
    {
      path: "../fonts/InterVariable-italic.woff2",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className)}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
